syntax = "proto3";

option go_package = "github.com/MidhunJithu/grpc-go-sample/blog/proto";

package blog;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

message Blog {
    string author_id = 2; // id of the author
    string title = 3; // title of the blog
    string content = 4; // content of the blog
}

message BlogId {
    string id = 1;
}

message BlogResponse {
    string id = 1;
    string author_id = 2;
    string title = 3;
    string content = 4;
    google.protobuf.Timestamp created_at = 5;
    google.protobuf.Timestamp updated_at = 6;
}

message ListFilter {
    string author_id = 1; // Filter by author_id
    string title = 2; // Filter by title
    google.protobuf.Timestamp created_at_gte = 3; // Filter by created_at
    int32 limit = 4; // Limit the number of blogs returned
    int32 page = 5; // for pagination
}

message UpdateBlogRequest {
    string id = 1;
    string title = 3;
    string content = 4;
}

service BlogService {
    rpc CreateBlog(Blog) returns (BlogId);
    rpc ReadBlog(BlogId) returns (BlogResponse);
    rpc ListBlogs(ListFilter) returns (stream BlogResponse);
    rpc UpdateBlog(UpdateBlogRequest) returns (BlogResponse);
    rpc DeleteBlog(BlogId) returns (google.protobuf.Empty);
}